dnl
dnl atom_types.m4
dnl
dnl M4 macro definitions for automatic Atom Type generation.
dnl This provides a pure m4-based and header-only implementation
dnl replacing the CMake-based type generation system.
dnl
dnl Copyright (c) 2026 OpenCog Foundation
dnl
changequote(`[', `]')dnl Change quote characters to avoid conflicts with C++ code
dnl
dnl Header-only initialization - types are declared and defined inline
dnl
define([ATOM_TYPES_HEADER_INIT], [dnl
/* File automatically generated by m4 from atom_types.script. Do not edit */
#ifndef _OPENCOG_ATOM_TYPES_H
#define _OPENCOG_ATOM_TYPES_H

#include <opencog/atoms/atom_types/types.h>
#include <opencog/atoms/atom_types/NameServer.h>

namespace opencog {

// Forward declarations and inline definitions (header-only)
])dnl
dnl
dnl Define a type inline (header-only approach)
dnl Usage: DEFINE_TYPE_INLINE(TYPE)
dnl
define([DEFINE_TYPE_INLINE], [dnl
ifelse([$1], [NOTYPE], [dnl
#ifndef _OPENCOG_NOTYPE_
#define _OPENCOG_NOTYPE_
// Set notype's code with the last possible Type code
static const Type NOTYPE = ((Type) -1);
#endif // _OPENCOG_NOTYPE_
], [dnl
inline Type& get_$1() {
    static Type type_instance = 0;
    return type_instance;
}
#define $1 get_$1()
])dnl
])dnl
dnl
dnl Close the atom types header
dnl
define([ATOM_TYPES_HEADER_END], [dnl

} // namespace opencog

#endif // _OPENCOG_ATOM_TYPES_H
])dnl
dnl
dnl Initialization function for registering types (header-only)
dnl This creates an inline function that registers all types
dnl
define([TYPE_REGISTRATION_INIT], [dnl
/* File automatically generated by m4. Do not edit */
#ifndef _OPENCOG_ATOM_TYPES_INIT_H
#define _OPENCOG_ATOM_TYPES_INIT_H

#include "atom_types.h"

namespace opencog {

// Header-only type registration - runs once via static initialization
inline void init_atom_types() {
    static bool initialized = false;
    if (initialized) return;
    initialized = true;
    
    nameserver().beginTypeDecls("core_types");
])dnl
dnl
dnl Register a type with nameserver (header-only)
dnl Usage: REGISTER_TYPE_INLINE(TYPE, PARENT, TYPE_NAME, SHORT_NAME)
dnl
define([REGISTER_TYPE_INLINE], [dnl
ifelse([$1], [NOTYPE], [], [dnl
ifelse([$2], [], [dnl
    $1 = nameserver().declType($1, "$3", "$4");
], [dnl
    $1 = nameserver().declType($2, "$3", "$4");
])dnl
])dnl
])dnl
dnl
dnl Close type registration
dnl
define([TYPE_REGISTRATION_END], [dnl
    
    nameserver().endTypeDecls();
}

// Static initializer to ensure types are registered
static struct AtomTypesInitializer {
    AtomTypesInitializer() { init_atom_types(); }
} _atom_types_initializer;

} // namespace opencog

#endif // _OPENCOG_ATOM_TYPES_INIT_H
])dnl
dnl
dnl Atom names header (inline constructors)
dnl
define([ATOM_NAMES_INIT], [dnl
/* File automatically generated by m4. Do not edit */
#ifndef _OPENCOG_ATOM_NAMES_H
#define _OPENCOG_ATOM_NAMES_H

#include "atom_types.h"
#include <opencog/atoms/base/Handle.h>
#include <opencog/atoms/base/Node.h>
#include <opencog/atoms/base/Link.h>

namespace opencog {

// Inline constructor helpers (header-only)
])dnl
dnl
dnl Define inline node constructor
dnl
define([NODE_CTOR_INLINE], [dnl
inline Handle $1(std::string name) {
    return createNode($2, std::move(name));
}
])dnl
dnl
dnl Define inline link constructor
dnl
define([LINK_CTOR_INLINE], [dnl
template<typename ...Atoms>
inline Handle $1(Atoms const&... atoms) {
    return createLink($2, atoms...);
}
])dnl
dnl
dnl Close atom names
dnl
define([ATOM_NAMES_END], [dnl

} // namespace opencog

#endif // _OPENCOG_ATOM_NAMES_H
])dnl
